version: '3.8'

services:
  php-backend:
    container_name: indexy-backend
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/var/www/.composer/cache:delegated
      - ./:/app
    user: "${UID}:${GID}"
    working_dir: /app/backend
    depends_on:
      - mysql
      - elasticsearch

  php-frontend:
    container_name: indexy-frontend
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/var/www/.composer/cache:delegated
      - ./:/app
    user: "${UID}:${GID}"
    working_dir: /app/frontend
    depends_on:
      - mysql
      - elasticsearch

  nginx:
    container_name: indexy-nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-backend
      - php-frontend

  mysql:
    container_name: indexy-mysql
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  elasticsearch:
    container_name: indexy-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  prometheus:
    container_name: indexy-prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: indexy-grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter
    container_name: indexy-node-exporter
    ports:
      - "9100:9100"

volumes:
  mysql_data:
  grafana_data:
